@extends('layouts.worktracker')
@section('content')
<x-worktracker.page-header title="قیمت‌گذاری" subtitle="نرخ مؤثر = نرخ پایه فعالیت × ضریب مشتری × ضریب پروژه؛ Override صریح نرخ نهایی است." />
<div class="wt-nav"><a href="{{ route('worktracker.dashboard') }}">داشبورد</a><a href="{{ route('worktracker.billing') }}">قیمت‌گذاری</a><a href="{{ route('worktracker.invoices.index') }}">فاکتورها</a></div>

<div class="wt-grid wt-grid-3">
<x-worktracker.panel title="مشتری جدید"><form method="post" action="{{ route('worktracker.billing.customers.store') }}" class="wt-form">@csrf
<label>نام<input name="name" required></label><label>شرکت<input name="company_name"></label><label>ضریب مشتری<input name="rate_multiplier" type="number" step="0.0001" value="1.0000" required></label><label>واحد پول<input name="currency" value="IRT" required></label><label>شروع اعتبار<input name="effective_from" type="datetime-local" value="{{ now()->format('Y-m-d\\TH:i') }}"></label><button>ثبت مشتری</button></form></x-worktracker.panel>
<x-worktracker.panel title="نوع فعالیت جدید"><form method="post" action="{{ route('worktracker.billing.activity-types.store') }}" class="wt-form">@csrf
<label>کد<input name="code" placeholder="development" required></label><label>عنوان<input name="name" placeholder="کدنویسی" required></label><label>نرخ پایه ساعتی<input name="base_hourly_rate_minor" type="number" min="0" required></label><label>واحد پول<input name="currency" value="IRT" required></label><label>شروع اعتبار<input name="effective_from" type="datetime-local" value="{{ now()->format('Y-m-d\\TH:i') }}"></label><label class="wt-check"><input type="checkbox" name="is_billable_default" value="1" checked> قابل صورتحساب</label><button>ثبت فعالیت</button></form></x-worktracker.panel>
<x-worktracker.panel title="پیش‌نمایش نرخ"><form id="pricing-preview" class="wt-form">@csrf
<label>پروژه<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label><label>فعالیت<select name="activity_type_id" required>@foreach($types as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></label><label>مدت (دقیقه)<input name="duration_minutes" type="number" value="60" min="1" required></label><label>در تاریخ<input name="effective_at" type="datetime-local" value="{{ now()->format('Y-m-d\\TH:i') }}"></label><button type="submit">محاسبه</button></form><div id="pricing-preview-result" class="wt-pricing-result">—</div></x-worktracker.panel>
</div>

<x-worktracker.panel title="مشتری‌ها و ضریب تاریخ‌دار"><x-worktracker.table><thead><tr><th>تنظیم مشتری</th></tr></thead><tbody>
@foreach($customers as $c)<tr><td><form method="post" action="{{ route('worktracker.billing.customers.update',$c->id) }}" class="wt-inline-form">@csrf<label>نام<input name="name" value="{{ $c->name }}" required></label><label>شرکت<input name="company_name" value="{{ $c->company_name }}"></label><label>ضریب<input name="rate_multiplier" type="number" step="0.0001" value="{{ $c->rate_multiplier }}" required></label><label>واحد<input name="currency" value="{{ $c->currency }}" required></label><label>اعمال از<input name="effective_from" type="datetime-local" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><button>ذخیره</button></form></td></tr>@endforeach
</tbody></x-worktracker.table></x-worktracker.panel>

<x-worktracker.panel title="Activity Typeها و نرخ پایه تاریخ‌دار"><x-worktracker.table><thead><tr><th>تنظیم Activity Type</th></tr></thead><tbody>
@foreach($types as $t)<tr><td>@if($t->user_id)<form method="post" action="{{ route('worktracker.billing.activity-types.update',$t->id) }}" class="wt-inline-form">@csrf<label>عنوان<input name="name" value="{{ $t->name }}" required></label><span class="wt-badge">{{ $t->code }}</span><label>نرخ پایه<input name="base_hourly_rate_minor" type="number" min="0" value="{{ $t->base_hourly_rate_minor }}" required></label><label>واحد<input name="currency" value="{{ $t->currency }}" required></label><label class="wt-check"><input type="checkbox" name="is_billable_default" value="1" @checked($t->is_billable_default)> Billable</label><label>اعمال از<input name="effective_from" type="datetime-local" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><button>ذخیره</button></form>@else<div class="wt-inline-form"><b>{{ $t->name }}</b><span>{{ $t->code }}</span><span>{{ number_format($t->base_hourly_rate_minor) }} {{ $t->currency }}</span><span class="wt-muted">سراسری / فقط خواندنی</span></div>@endif</td></tr>@endforeach
</tbody></x-worktracker.table></x-worktracker.panel>

<x-worktracker.panel title="پروژه‌ها، مشتری و ضریب پروژه"><x-worktracker.table><thead><tr><th>پروژه</th><th>مشتری</th><th>ضریب مشتری</th><th>ضریب پروژه</th><th>فعال</th><th>اعمال ضریب از</th><th></th></tr></thead><tbody>
@foreach($projects as $p)<tr><td>{{ $p->name }}</td><td colspan="6"><form method="post" action="{{ route('worktracker.billing.projects.update',$p->id) }}" class="wt-inline-form">@csrf<select name="customer_id"><option value="">بدون مشتری</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected($p->customer_id===$c->id)>{{ $c->name }}</option>@endforeach</select><span>{{ $p->customer?->rate_multiplier ?? '1.0000' }}</span><input name="rate_multiplier" type="number" step="0.0001" value="{{ $p->rate_multiplier ?? 1 }}" required><label class="wt-check"><input type="checkbox" name="is_billable_default" value="1" @checked($p->is_billable_default)> پروژه قابل صورتحساب</label><input name="effective_from" type="datetime-local" value="{{ now()->format('Y-m-d\\TH:i') }}" required><button>ذخیره</button></form></td></tr>@endforeach
</tbody></x-worktracker.table></x-worktracker.panel>

<x-worktracker.panel title="نرخ استثنا"><p class="wt-muted">Override نرخ نهایی است؛ ضرایب دوباره روی آن ضرب نمی‌شوند.</p><form method="post" action="{{ route('worktracker.billing.overrides.store') }}" class="wt-form wt-form-grid">@csrf
<label>مشتری<select name="customer_id"><option value="">—</option>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></label><label>پروژه<select name="project_id"><option value="">—</option>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label><label>فعالیت<select name="activity_type_id">@foreach($types as $t)<option value="{{ $t->id }}">{{ $t->name }}</option>@endforeach</select></label><label>نرخ نهایی ساعتی<input name="hourly_rate_minor" type="number" min="0" required></label><label>واحد<input name="currency" value="IRT" required></label><label>از تاریخ<input name="effective_from" type="datetime-local" required></label><label>تا تاریخ<input name="effective_until" type="datetime-local"></label><label>توضیح<input name="note"></label><button>ثبت نرخ استثنا</button></form></x-worktracker.panel>

<script>document.getElementById('pricing-preview')?.addEventListener('submit',async(e)=>{e.preventDefault();const f=e.currentTarget,r=await fetch(@json(route('worktracker.billing.preview')),{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':f.querySelector('[name="_token"]').value},body:new FormData(f)}),o=document.getElementById('pricing-preview-result');if(!r.ok){o.textContent='خطا در محاسبه نرخ';return;}const d=await r.json();o.innerHTML=`نرخ پایه تاریخی: <b>${Number(d.base_rate_minor).toLocaleString()}</b> × مشتری <b>${d.customer_multiplier}</b> × پروژه <b>${d.project_multiplier}</b><br>نرخ مؤثر: <b>${Number(d.effective_rate_minor).toLocaleString()} ${d.currency}</b><br>مبلغ: <b>${Number(d.amount_minor).toLocaleString()} ${d.currency}</b><br><small>${d.resolution_source}</small>`;});</script>
@endsection
