<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>WorkTracker.Agent</AssemblyName>
    <RootNamespace>WorkTracker.Agent</RootNamespace>
    <Version>0.1.0-alpha.7.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Storage\local-schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
