<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('activity_sessions', function (Blueprint $table) {
            $table->uuid('id')->primary(); // generated by client for idempotent sync
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignUuid('device_id')->constrained()->cascadeOnDelete();
            $table->foreignUlid('project_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignUlid('task_id')->nullable()->constrained('tasks')->nullOnDelete();
            $table->string('source', 40);
            $table->string('process_name')->nullable();
            $table->text('executable_path')->nullable();
            $table->text('window_title')->nullable();
            $table->decimal('classification_confidence', 5, 4)->nullable();
            $table->text('classification_reason')->nullable();
            $table->dateTimeTz('started_at');
            $table->dateTimeTz('ended_at');
            $table->unsignedInteger('duration_seconds');
            $table->unsignedInteger('idle_seconds')->default(0);
            $table->text('note')->nullable();
            $table->boolean('is_billable')->default(false);
            $table->unsignedInteger('version')->default(1);
            $table->dateTimeTz('created_at_device')->nullable();
            $table->dateTimeTz('updated_at_device')->nullable();
            $table->timestampsTz();
            $table->index(['user_id','started_at']);
            $table->index(['device_id','started_at','ended_at']);
            $table->index(['project_id','started_at']);
            // Intentionally no uniqueness or overlap constraint across devices.
        });
    }
    public function down(): void { Schema::dropIfExists('activity_sessions'); }
};
